version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5  # GitHub default.
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"