version: 2.1

# XXX: rockstar (20 Apr 2023) - This orb and executor are holdovers
# from the legacy system, and are used for the slack notification.
# Once that slack notification is also simplified, these can go.
orbs:
  slack: circleci/slack@4.10.1

executors:
  linux-python:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/python:<< parameters.tag >>

commands:
  install-hatch:
    description: "Install hatch"
    steps:
      - run:
          command: "pip3 install hatch"

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - install-hatch
      - run:
          command: hatch build
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - install-hatch
      - run:
          command: hatch run test
  check:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - install-hatch
      - run:
          command: hatch run check
  publish:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - install-hatch
      - run:
          name: "Validate tag"
          description: |
            Ensure that the tag matches the version of the python library. If those
            two versions don't match, don't continue to publish.
          command: |
            if [ ! [ << pipeline.git.tag >> = "v$(hatch version)"]]; then
              echo Git tag does not match the python library version. Aborting publish job.
              exit 1
            fi
      - run:
          name: "Build package"
          command: hatch build
      - run:
          name: "Publish to PyPI"
          command: hatch publish -n -a $PYPI_TOKEN -u __token__

  send-slack-notification:
    parameters:
      executor_tag:
        description: "The Python env that the executor uses"
        type: string
        default: "3.8.12"
    executor:
      name: linux-python
      tag: << parameters.executor_tag >>
    steps:
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New SDK Release! ${CIRCLE_TAG:1} :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "More info:\nhttps://github.com/Watchfulio/watchful-py/releases/tag/$CIRCLE_TAG\nhttps://pypi.org/project/watchful/${CIRCLE_TAG:1}/"
                    }
                  ]
                }
              ]
            }

workflows:
  core:
    jobs:
      - build
      - test
      - check
  release:
    when: << pipeline.git.tag >>
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
      - send-slack-notification:
          requires:
            - publish
          filters:
            tags:
              only: /.*/
