version: 2.1

orbs:
  slack: circleci/slack@4.10.1

commands:
  install-hatch:
    description: "Install hatch"
    steps:
      - run:
          command: "pip3 install hatch"

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
      - install-hatch
      - run:
          command: hatch build
      - save_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
          paths:
            - ".hatch-env"
            - "~/.cache/pip"
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
      - install-hatch
      - run:
          command: hatch run test
      - save_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
          paths:
            - ".hatch-env"
            - "~/.cache/pip"
  check:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
      - install-hatch
      - run:
          command: hatch run check
      - save_cache:
          key: watchful-py-{{ checksum "pyproject.toml" }}
          paths:
            - ".hatch-env"
            - ".mypy_cache"
            - ".ruff_cache"
            - "~/.cache/pip"
  publish:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - install-hatch
      - run:
          name: "Validate tag"
          description: |
            Ensure that the tag matches the version of the python library. If those
            two versions don't match, don't continue to publish.
          command: |
            if [ ! [ << pipeline.git.tag >> = "v$(hatch version)"]]; then
              echo Git tag does not match the python library version. Aborting publish job.
              exit 1
            fi
      - run:
          name: "Build package"
          command: hatch build
      - run:
          name: "Publish to PyPI"
          command: hatch publish -n -a $PYPI_TOKEN -u __token__

  send-slack-notification:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New SDK Release! ${CIRCLE_TAG} :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "More info:\nhttps://github.com/Watchfulio/watchful-py/releases/tag/$CIRCLE_TAG\nhttps://pypi.org/project/watchful/${CIRCLE_TAG:1}/"
                    }
                  ]
                }
              ]
            }

workflows:
  core:
    jobs:
      - build
      - test
      - check
  release:
    when: << pipeline.git.tag >>
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
      - send-slack-notification:
          requires:
            - publish
          context: slack
          filters:
            tags:
              only: /.*/

